Browser("Afore, Pensiones y Préstamos").WinObject("Notification bar").WinButton("Show all content").Click @@ hightlight id_;_2011727904_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Afore, Pensiones y Préstamos").Link("Afore Profuturo").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Afore, Pensiones y Préstamos").Link("Afore Profuturo")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Qué es Afore? - Profuturo").Link("¿Quién las regula?Regula").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Qué es Afore? - Profuturo").Link("¿Quién las regula?Regula")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Qué es Afore? - Profuturo_2").Link("¿Para qué sirve tu Afore?").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Qué es Afore? - Profuturo 2").Link("¿Para qué sirve tu Afore?")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Para qué sirve mi Afore?").Link("¿Para qué sirve tu AFORE?").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Para qué sirve mi Afore?").Link("¿Para qué sirve tu AFORE?")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Para qué sirve mi Afore?").Link("¿Por qué Profuturo?").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Para qué sirve mi Afore?").Link("¿Por qué Profuturo?")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").Link("Ver mi futuro").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").Link("Ver mi futuro")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebEdit("age").Set "35" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebEdit("age")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebEdit("name").Set "Juan Perez" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebEdit("name")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement_2").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement 2")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebEdit("income").Set "15000" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebEdit("income")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement_3").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement 3")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement_4").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement 4")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebList("where").Select "IMSS" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebList("where")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement_5").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("¿Por qué Profuturo | Profuturo").WebElement("WebElement 5")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").WebEdit("anios").Set "15" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").WebEdit("anios")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").WebList("genero").Select "MASCULINO" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").WebList("genero")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").WebEdit("ahorro-mes").Set "1000" @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").WebEdit("ahorro-mes")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").Link("Grupo Profuturo").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Calculadora de retiro").Link("Grupo Profuturo")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Información corporativa").Link("Cultura Corporativa").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Información corporativa").Link("Cultura Corporativa")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Cultura corporativa -").Link("Contacto").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Cultura corporativa -").Link("Contacto")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("Afore, Pensiones y Préstamos").Page("Contacto. Solicita información").Link("Mi Registro en Profuturo").Click @@ hightlight id_;_Browser("Afore, Pensiones y Préstamos").Page("Contacto. Solicita información").Link("Mi Registro en Profuturo")_;_script infofile_;_ZIP::ssf23.xml_;_
'Cambio 1 Cambio para demostrar actualización al script
'Cambio 2 Prueba de actualización
